"""correction in ticket history table

Revision ID: 4a3aa2372ed2
Revises: fd2ea5c045b6
Create Date: 2026-06-27 11:32:12.846339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3aa2372ed2'
down_revision: Union[str, Sequence[str], None] = 'fd2ea5c045b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
