"""fix spelling in ticket relationship with ticket history

Revision ID: 68970cc217c4
Revises: 00b071c697fb
Create Date: 2026-09-23 04:55:07.946979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68970cc217c4'
down_revision: Union[str, Sequence[str], None] = '00b071c697fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
